config/routes.rb
Rails.application.routes.draw do
  get 'post_comments/new'
  get 'post_comments/edit'
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  get 'home/top'
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: {message: 'タイトルを入力してください！'}
  validates :body, presence: {message: '本文を入力してください！'}, length: {minimum: 5, message: '5文字以上入力してください！'}

  attachment :image

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy


end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: {message: '入力してください！'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image

  has_many :posts
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    like = current_user.likes.new(post_id: post.id)
    like.save
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    like = current_user.likes.find_by(post_id: post.id)
    like.destroy
    redirect_to post_path(post)
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = @post.id
    comment.save
    flash[:notice] = 'コメントを投稿しました！'
    redirect_to post_path(@post)
  end

 def destroy
   @post_comment = PostComment.find(params[:id])
   @post_comment.destroy
   flash[:notice] = 'コメントを削除しました！'
   redirect_to posts_path
 end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment, :user_id, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!

  def index
    @posts = Post.all.order(created_at: 'desc')
    @post = Post.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = '投稿しました！'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comments = @post.post_comments
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = '編集しました！'
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = '削除しました！'
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :image, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!

  def index
    @users = User.all.order(created_at: 'desc')
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all
    @post_comments = @user.post_comments
    @likes = @user.likes
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :profile, :user_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="top-background">
  <div class="container">
    <h1 class="top-headline">PassOn</h1>
    <p class="top-line">いろんな人と繋がってみよう！</p>
    <%= link_to 'PassOnをはじめる', new_user_registration_path, class: "btn btn-success btn-lg btn-block signup-btn" %>
    <%= link_to 'ログイン', new_user_session_path, class: "btn btn-default btn-lg btn-block login-btn" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PassOn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid header">
          <div class="navbar-header">
      			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
              <span class="sr-only">Toggle navigation</span>
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
            </button>
            <a class="navbar-brand header-title" href="#">PassOn</a>
          </div>
          <div class="collapse navbar-collapse" id="navbarEexample">
      			<ul class="nav navbar-nav navbar-right">
              <!-- ログイン時 -->
              <% if user_signed_in? %>
        				<li>
                  <%= link_to root_path do %>
                    <span class="glyphicon glyphicon-home" aria-hidden="true"></span>ホーム
                  <% end %>
                </li>
        				<li>
                  <%= link_to user_path(current_user) do %>
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>マイページ
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path do %>
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>ユーザー一覧
                  <% end %>
                </li>
        				<li>
                  <%= link_to new_post_path do %>
                    <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>投稿
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>ログアウト
                  <% end %>
                </li>
                <!-- ログアウト時 -->
              <% else %>
                <li>
                  <%= link_to new_user_registration_path do %>
                    <span class="glyphicon glyphicon-unchecked" aria-hidden="true"></span>新規登録
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path do %>
                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>ログイン
                  <% end %>
                </li>
              <% end %>
      			</ul>
      		</div>
        </div>
      </nav>
    </header>
    <% if flash[:notice] %>
     <p class="flash"><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="post-form">
    <!-- <h3 class="form-factor">タイトル</h3>
    <input type="text" class="form-factor"><br>
    <textarea class="form-factor textarea"></textarea>
    <input type="file" class="form-factor">
    <input type="submit" value="投稿"> -->
    <%= form_for @post do |f| %>
      <%= f.text_field :title, class: 'form-factor', placeholder: 'タイトル' %><br>
      <%= f.text_area :body, class: 'form-factor textarea', placeholder: '本文' %><br>
      <!-- 画像フォーム挿入 -->
      <%= f.attachment_field :image, class: 'form-factor' %><br>
      <%= f.submit "保存" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="container-fluid">
  	<div class="row">
  		<div class="main col-lg-7">
        <% @posts.each do |post| %>
          <div class="post-wrapper">
            <%= attachment_image_tag post.user, :user_image, :fill, 100, 100, class: 'user-image', fallback: 'no_image.jpg' %>
            <%= link_to post.user.nickname, user_path(post.user), class: 'user-name' %>
            <%= link_to post.title, post_path(post), class: 'post-title' %>
            <%= attachment_image_tag post, :image, :fill, 600, 350, class: 'post-image' %>
            <p class="post-body"><%= post.body %></p>
            <div class="favorite-action">
              <% if post.liked_by?(current_user) %>
                <%= link_to post_likes_path(post), method: :delete, class: 'like-btn' do %>
                  <span class="glyphicon glyphicon-heart liked-heart" aria-hidden="true"></span><%= post.likes.count %> いいね
                <% end %>
              <% else %>
                <%= link_to post_likes_path(post), method: :post, class: 'like-btn' do %>
                  <span class="glyphicon glyphicon-heart unliked-heart" aria-hidden="true"></span><%= post.likes.count %> いいね
                <% end %>
              <% end %>
              <%= link_to post_path(post) do %>
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span><%= post.post_comments.count %>件 コメント
              <% end %>
            </div>
            <div class="edit-action">
            <% if post.user == current_user %>
              <%= link_to '編集', edit_post_path(post) %>
              <%= link_to '削除', post_path(post), method: :delete, "data-confirm" => '投稿を削除してもよろしいですか？' %>
            <% end %>
            </div>
          </div>
        <% end %>
      </div>
  		<div class="side col-lg-5">
        <div class="user-info">
          <%= attachment_image_tag current_user, :user_image, :fill, 100, 100, class: 'user-image', fallback: 'no_image.jpg' %>
          <%= link_to current_user.nickname, user_path(current_user), class: 'user-name' %>
          <%= link_to 'アカウントを編集する', edit_user_path(current_user), class: 'user-setting' %>
        </div>
        <div class="post-form">
          <%= form_for @post do |f| %>
          <% if @post.errors.messages[:title].any? %>
            <p class="error"><%= @post.errors.messages[:title][0] %></p>
          <% end %>
            <%= f.text_field :title, class: 'form-factor', placeholder: 'タイトル' %><br>
          <% if @post.errors.messages[:body].any? %>
            <p class="error"><%= @post.errors.messages[:body][0] %></p>
          <% end %>
            <%= f.text_area :body, class: 'form-factor textarea', placeholder: '本文' %><br>
            <!-- 画像フォーム挿入 -->
            <%= f.attachment_field :image, class: 'form-factor' %><br>
            <%= f.submit "投稿" %>
          <% end %>
        </div>
      </div>
  	</div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="post-form">
    <%= form_for @post do |f| %>
    <% if @post.errors.messages[:title].any? %>
      <p class="error"><%= @post.errors.messages[:title][0] %></p>
    <% end %>
      <%= f.text_field :title, class: 'form-factor', placeholder: 'タイトル' %><br>
    <% if @post.errors.messages[:body].any? %>
      <p class="error"><%= @post.errors.messages[:body][0] %></p>
    <% end %>
      <%= f.text_area :body, class: 'form-factor textarea', placeholder: '本文' %><br>
      <!-- 画像フォーム挿入 -->
      <%= f.attachment_field :image, class: 'form-factor' %><br>
      <%= f.submit "投稿" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="post-wrapper">
    <%= attachment_image_tag @post.user, :user_image, :fill, 100, 100, class: 'user-image', fallback: 'no_image.jpg' %>
    <%= link_to @post.user.nickname, user_path(@post.user), class: 'user-name' %>
    <a href="#" class="post-title"><%= @post.title %></a>
    <%= attachment_image_tag @post, :image, :fill, 600, 350, class: 'post-image' %>
    <p class="post-body"><%= @post.body %></p>
    <div class="favorite-action">
      <% if @post.liked_by?(current_user) %>
        <%= link_to post_likes_path(@post), method: :delete, class: 'like-btn' do %>
          <span class="glyphicon glyphicon-heart liked-heart" aria-hidden="true"></span><%= @post.likes.count %> いいね
        <% end %>
      <% else %>
        <%= link_to post_likes_path(@post), method: :post, class: 'like-btn' do %>
          <span class="glyphicon glyphicon-heart unliked-heart" aria-hidden="true"></span><%= @post.likes.count %> いいね
        <% end %>
      <% end %>
      <%= link_to post_path(@post) do %>
        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span><%= @post.post_comments.count %>件 コメント
      <% end %>
    </div>
    <div class="edit-action">
    <% if @post.user == current_user %>
      <%= link_to '編集', edit_post_path(@post) %>
      <%= link_to '削除', post_path(@post), method: :delete, "data-confirm" => '投稿を削除してもよろしいですか？' %>
    <% end %>
    </div>
  </div>

  <div class="post-form">
    <%= form_for [@post, @post_comment] do |f| %>
      <% if @post_comment.errors.any? %>
        <p class="error"><%= @post_comment.errors.messages[:comment][0] %></p>
      <% end %>
      <%= f.text_area :comment, placeholder: 'コメントをここに', class: 'form-factor textarea' %><br>
      <%= f.submit 'コメントをする' %>
    <% end %>
  </div>

  <% @post_comments.each do |post_comment| %>
  <div class="comment-wrapper">
    <%= attachment_image_tag post_comment.user, :user_image, :fill, 100, 100, class: 'user-image', fallback: 'no_image.jpg' %>
    <%= link_to post_comment.user.nickname, user_path(post_comment.user), class: 'user-name' %>
    <p class="comment-content"><%= post_comment.comment %></p>
    <div class="edit-action">
      <% if current_user == post_comment.user %>
        <%= link_to '削除', post_post_comment_path(@post, post_comment), method: :delete, class: 'destroy-link' %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="form-wrapper">
    <%= form_for @user do |f| %>
      <%= f.text_field :nickname, autofocus: true, placeholder: 'ニックネーム', class: 'form-factor' %><br>
      <%= f.text_area :profile, placeholder: '自己紹介文', class: 'form-factor' %><br>
      <%= attachment_image_tag @user, :user_image, :fill, 100, 100, class: 'form-factor', fallback: 'no_image.jpg' %><br>
      <%= f.attachment_field :user_image, placeholder: 'プロフィール画像', class: 'form-factor' %><br>
      <%= f.submit '保存' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <% @users.each do |user| %>
  <div class="user-info">
    <%= attachment_image_tag user, :user_image, :fill, 100, 100, class: 'user-image', fallback: 'no_image.jpg' %>
    <%= link_to user.nickname, user_path(user), class: 'user-name' %>
    <% if user == current_user %>
      <%= link_to 'アカウントを編集する', edit_user_path(user), class: 'user-setting' %>
    <% end %>
    <p class="self-intro"><%= user.profile %></p>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="user-info">
    <%= attachment_image_tag @user, :user_image, :fill, 100, 100, class: 'user-image', fallback: 'no_image.jpg' %>
    <a href="#" class="user-name"><%= @user.nickname %></a>
    <% if @user == current_user %>
      <%= link_to 'アカウントを編集する', edit_user_path(@user), class: 'user-setting' %>
    <% end %>
    <p class="self-intro"><%= @user.profile %></p>
  </div>
  <div class="user-action-info">
    <!-- タブ・メニュー -->
    <ul class="nav nav-tabs">
    	<li class="active">
        <%= link_to '投稿一覧', '#sampleContentA', data: {toggle: 'tab'} %>
      </li>
    	<li><a href="#sampleContentB" data-toggle="tab">コメント</a></li>
    	<li><a href="#sampleContentC" data-toggle="tab">いいね</a></li>
    </ul>

    <!-- タブ内容 -->
    <div class="tab-content">
    	<div class="tab-pane active" id="sampleContentA">
    		<p>
          <% @posts.each do |post| %>
            <div class="post-wrapper">
              <%= attachment_image_tag @user, :user_image, :fill, 100, 100, class: 'user-image', fallback: 'no_image.jpg' %>
              <a href="#" class="user-name"><%= @user.nickname %></a>
              <%= link_to post.title, post_path(post), class: 'post-title' %>
              <%= attachment_image_tag post, :image, :fill, 600, 350, class: 'post-image' %>
              <p class="post-body"><%= post.body %></p>
              <div class="favorite-action">
                <% if post.liked_by?(current_user) %>
                  <%= link_to post_likes_path(post), method: :delete, class: 'like-btn' do %>
                    <span class="glyphicon glyphicon-heart liked-heart" aria-hidden="true"></span><%= post.likes.count %> いいね
                  <% end %>
                <% else %>
                  <%= link_to post_likes_path(post), method: :post, class: 'like-btn' do %>
                    <span class="glyphicon glyphicon-heart unliked-heart" aria-hidden="true"></span><%= post.likes.count %> いいね
                  <% end %>
                <% end %>
                <%= link_to post_path(post) do %>
                  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span><%= post.post_comments.count %>件 コメント
                <% end %>
              </div>
              <div class="edit-action">
              <% if @user == current_user %>
                <%= link_to '編集', edit_post_path(post) %>
                <%= link_to '削除', post_path(post), method: :delete, "data-confirm" => '投稿を削除してもよろしいですか？' %>
              <% end %>
              </div>
            </div>
          <% end %>
        </p>
    	</div>
    	<div class="tab-pane" id="sampleContentB">
    		<p>
          <% @post_comments.each do |post_comment| %>
          <div class="comment-wrapper">
            <%= attachment_image_tag post_comment.user, :user_image, :fill, 100, 100, class: 'user-image', fallback: 'no_image.jpg' %>
            <%= link_to post_comment.user.nickname, user_path(post_comment.user), class: 'user-name' %>
            <p class="comment-content"><%= post_comment.comment %></p>
            <div class="edit-action">
              <% if current_user == post_comment.user %>
                <%= link_to '削除', post_post_comment_path(post_comment.post, post_comment), method: :delete, class: 'destroy-link' %>
              <% end %>
            </div>
          </div>
          <% end %>
        </p>
    	</div>
    	<div class="tab-pane" id="sampleContentC">
    		<p>
        <% @likes.each do |like| %>
          <% post = Post.find_by(id: like.post_id) %>
          <div class="post-wrapper">
            <%= attachment_image_tag post.user, :user_image, :fill, 100, 100, class: 'user-image', fallback: 'no_image.jpg' %>
            <%= link_to post.user.nickname, user_path(post.user), class: 'user-name' %>
            <%= link_to post.title, post_path(post), class: 'post-title' %>
            <%= attachment_image_tag post, :image, :fill, 600, 350, class: 'post-image' %>
            <p class="post-body"><%= post.body %></p>
            <div class="favorite-action">
              <% if post.liked_by?(current_user) %>
                <%= link_to post_likes_path(post), method: :delete, class: 'like-btn' do %>
                  <span class="glyphicon glyphicon-heart liked-heart" aria-hidden="true"></span><%= post.likes.count %> いいね
                <% end %>
              <% else %>
                <%= link_to post_likes_path(post), method: :post, class: 'like-btn' do %>
                  <span class="glyphicon glyphicon-heart unliked-heart" aria-hidden="true"></span><%= post.likes.count %> いいね
                <% end %>
              <% end %>
              <%= link_to post_path(post) do %>
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span><%= post.post_comments.count %>件 コメント
              <% end %>
            </div>
            <div class="edit-action">
            <% if post.user == current_user %>
              <a href="#">編集</a>
              <a href="#" class="destroy-link">削除</a>
            <% end %>
            </div>
          </div>
        <% end %>
        </p>
    	</div>
    </div>
  </div>
</div>